
trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Run a multi-line script'
  
- script: java -jar target/*.jar

